require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120